version: "3.5"
services:
  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otelcol-prom-only.yml:/etc/otelcol/otelcol-prom-only.yml"
    command: --config /etc/otelcol/otelcol-prom-only.yml
    ports:
      - "8889:8889"
  synthetic_trace_generator:
    networks:
      - backend
    image: albteo/synthetic-load-generator:latest
    volumes:
      - "./hipster-shop.json:/etc/synthetic-trace-generator/hipster-shop.json"
    environment: 
      - JAEGER_COLLECTOR_URL=http://otel_collector:14278
      - TOPOLOGY_FILE=/etc/synthetic-trace-generator/hipster-shop.json
  prometheus:
    expose:
      - "9090"
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
 
networks:
  backend:
